### ISSUE TITLE
建议画一张草图方便理解

### ISSUE THREAD

**Issue by dfaofeng** [cxDosx/OneStrokeRedPacket#1]
x是对应的横竖,y对应的横竖,不怎么好理解

**Comment by cxDosx** [comment]
x轴代表横坐标，y轴代表纵坐标，原点(1,1)在左上角，直接带入坐标系就可以了

**Comment by dfaofeng** [comment]
![QQ截图20201203144015](https://user-images.githubusercontent.com/14891398/100973487-990ace00-3575-11eb-8016-1a83c1ee2c3e.png)
下一个坐标点x5,y4
下一个坐标点x4,y4
下一个坐标点x4,y5
下一个坐标点x3,y5
下一个坐标点x3,y4
下一个坐标点x2,y4
下一个坐标点x2,y5
下一个坐标点x1,y5
下一个坐标点x1,y4
下一个坐标点x1,y3
下一个坐标点x2,y3
下一个坐标点x3,y3
下一个坐标点x4,y3
下一个坐标点x5,y3
下一个坐标点x5,y2
下一个坐标点x4,y2
下一个坐标点x3,y2
下一个坐标点x2,y2
下一个坐标点x1,y2
下一个坐标点x1,y1
下一个坐标点x2,y1
下一个坐标点x3,y1
下一个坐标点x4,y1
下一个坐标点x5,y1
是否是这样的
但是如果起始点不知道咋搞

**Comment by cxDosx** [comment]
你的图片上，蓝色数字标注的是X，紫色数字标注的是Y，初始坐标在最初的版本中没有打印，[现已更新上去了](https://github.com/cxDosx/OneStrokeRedPacket/commit/4d000b9476fce32799929c28d2f09f3c5961a28e)，路径根据你提供的数据来看是没有错误的。

如果坐标点比较难以观察，你可以将[此处的代码](https://github.com/cxDosx/OneStrokeRedPacket/blob/4d000b9476fce32799929c28d2f09f3c5961a28e/src/main/kotlin/Main.kt#L34)解除注释，可能会帮到你。
